name: Release and Publish to NPM

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publish to NPM
        uses: js-actions/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
